language: generic 
sudo: require
services:
    - docker

before_install:
    - docker build -t mateusaueressig/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mateusaueressig/docker-react npm run test -- --coverage